### ISSUE TITLE
Using sedlex with jbuilder?

### ISSUE THREAD

**Issue by adrieng** [alainfrisch/sedlex#46]
I'd like to use sedlex with jbuilder, however jbuilder does not support normal ppx rewriters for performance reasons: https://github.com/janestreet/jbuilder/issues/14

As mentioned in the discussion above, one solution is to port sedlex to use the [ocaml-migrate-parsetree](http://github.com/let-def/ocaml-migrate-parsetree) driver API. One other would be to use [ppx_driver](http://github.com/janestreet/ppx_driver), but that looks like more work (and dependencies?) to me.

I actually did the porting work, so if anybody is interested, I will submit a pull request.

**Comment by alainfrisch** [comment]
Yes, thanks, a PR to switch to jbuilder will be appreciated!

**Comment by smolkaj** [comment]
Has this been fixed? I'm using the following ugly workaround for now, but it's probably brittle:
```
(rule
 ((targets (Lexer.ml))
  (deps    (Lexer.sedlex.ml))
  (action  (run ${ocaml_where}/../sedlex/ppx_sedlex ${<} -o ${@}))))
```
