### ISSUE TITLE
Move the build system to jbuilder?

### ISSUE THREAD

**Issue by bikallem** [alainfrisch/sedlex#48]
@alainfrisch @Drup Is there any interest in moving the current build system of `sedlex, ppx_tools, gen` to jbuilder? I will do the migration.

**Comment by alainfrisch** [comment]
ppx_tools: I'd rather not switch unless there is a strong argument in favor. I prefer to minimize dependencies of this package as much as possible.

sedlex: I don't really care; I'll let other maintainers comment.

gen: not under my control.

**Comment by rgrinberg** [comment]
Note that people should never use ppx_tools anymore unless they really know what they're doing. Ppx_tools_versioned should almost always be preferred as it will usually cause less grief for users.

That being said, I still think that ppx_tools should switch to jbuilder when installed from opam. jbuilder is much better at building and installing all the correct files and their variations (bytecode vs native, cmti, mli's, etc.) But that doesn't mean that ppx_tools can't keep its make based build system for those who would like to minimize dependencies.

@alainfrisch What do you think? Can we add a jbuild file just for opam to use?

**Comment by alainfrisch** [comment]
For ppx_tools, ok for add a jbuild file, but be prepared to be asked to update it!  (Although I hope people will switch to ppx_tools_versioned.)

For sedlex, there is also #46
